### ISSUE TITLE
Forks Over Knives Example

### ISSUE THREAD

**Issue by 4750moorem** [sean-public/RecipeFilter#1]
This site seems to not fall into into the redesign div correctly. It just copied the whole page into the div and didn't wrap or fit in well.
![image](https://user-images.githubusercontent.com/20134112/33384491-ce5c6296-d4eb-11e7-95bc-511dda76178f.png)

**Comment by edireson** [comment]
Sorry to hijack this old issue, but I'm wondering if you'd be open to accepting PRs that would sanitize the recipe view for display/printing purposes. Probably too big of a task to have robust coverage of all sites, but seems doable for any that make JSON-LD versions available? @sean-public

**Comment by sean-public** [comment]
> Sorry to hijack this old issue, but I'm wondering if you'd be open to accepting PRs that would sanitize the recipe view for display/printing purposes.

I think that's outside the [on purpose] very limited scope of the extension. A great many of the sites I've seen use recipe cards that have a `print` button inside them that formats it as the authors intended for printing.
