### ISSUE TITLE
Saveur Recipes Not Recognized 

### ISSUE THREAD

**Issue by curts** [sean-public/RecipeFilter#18]
https://www.saveur.com/perfect-chocolate-chip-cookies-recipe/
https://www.saveur.com/ceviche-verde-with-homemade-tortilla-chips-recipe/

**Comment by sean-public** [comment]
Those recipes start "above the fold", so there's nothing for this extension to do. If it cloned the huge recipe layout they use, it would be as wide and as tall as the page anyway. The layout they use isn't the offending style Recipe Filter is meant to help with.
