### ISSUE TITLE
Pioneer Woman Blog Recipes formatting is awful

### ISSUE THREAD

**Issue by kpetrich** [sean-public/RecipeFilter#2]
http://thepioneerwoman.com/cooking/braised-short-ribs-heaven-on-a-plate/

I tried other blogs, they look awesome! Pioneer Woman is jacked up.

**Comment by worc** [comment]
is this really closed or just fixed, pending release? i'm not seeing the changes make their way to the extension installed on my browser.

**Comment by sean-public** [comment]
Yes, PR #4 fixed this issue and it is slated for the next release.

The extension will be repacked and uploaded to the Google Web Store after some more bugs are fixed and at least one enhancement made that is in progress. The version number will increment so Chrome will auto-update at that time. I think that will be in the next day or two. Thank you for your patience -- in the meantime you can of course tell it not to run on Pioneer Woman until the extension is updated in the Web Store.
