### ISSUE TITLE
hmcason.wixsite.com not recognized

### ISSUE THREAD

**Issue by cbenard** [sean-public/RecipeFilter#23]
https://hmcason.wixsite.com/thegreengoddess/single-post/2020/06/19/Best-EVER-Vegan-Coleslaw

**Comment by sean-public** [comment]
The recipe and the notes about it are all in the same div, so this page is fundamentally incompatible with how Recipe Filter works and there is no JSON-LD object either to format. Since it's a flat, generic content body, there's not a lot we can do with this one!
