### ISSUE TITLE
_rf_header not displaying at the top of the cloned element

### ISSUE THREAD

**Issue by PBudgie** [sean-public/RecipeFilter#27]
When the browser window is wider than a certain point, the _rf_header element shows up incorrectly. It is aligned on the left instead of the top. This seems to happen when the text "Recipe Filter" is displayed on 2 lines.
![Screen Shot 2020-08-13 at 4 07 09 PM](https://user-images.githubusercontent.com/3944228/90195750-21732200-dd7f-11ea-83c5-1db2961ebc6e.png)

However, when the window is narrower, it shows up correctly.
![Screen Shot 2020-08-13 at 4 09 07 PM](https://user-images.githubusercontent.com/3944228/90195821-554e4780-dd7f-11ea-8d8d-67e5f197612f.png)

Link to the site in the example: https://tasty.co/recipe/the-best-chewy-chocolate-chip-cookies
This may be site-specific because it looks like the cloned element has a forced flex display but I wasn't able to isolate whether this was the problem.

**Comment by sean-public** [comment]
> the cloned element has a forced flex display

That looks like exactly the issue! A display reset on the CSS for the modal would correct it, I think.

**Comment by sean-public** [comment]
This site has changed in the last couple of years. It looks like a good candidate to choose `disable on this site` because the recipes are now near the top and laid out in a wide format that won't clone well into a modal.
