### ISSUE TITLE
Smitten Kitchen not filtered

### ISSUE THREAD

**Issue by y8s** [sean-public/RecipeFilter#30]
https://smittenkitchen.com/2013/11/apple-and-herb-stuffing-for-all-seasons/ for example

Great extension otherwise. Just trynna make my stuffing. 💯

**Comment by sean-public** [comment]
They intentionally didn't put their recipes into an element with an identifier or class we can search for. Also, they are using CSS to hide the byline and a `Jump to recipe` link at the top of the article (right near the date). Sorry, but I can't add support for this type of site.

<img width="578" alt="image" src="https://github.com/sean-public/RecipeFilter/assets/21961562/b0e925de-2ab9-42da-8362-7c976260e8df">

Note the `display: none`.
