### ISSUE TITLE
Publish the Safari extension as an iOS Safari Web Extension App

### ISSUE THREAD

**Issue by hjdarnel** [sean-public/RecipeFilter#33]
Theoretically, I think Safari web extensions are cross-platform now. I stumbled across [this blog post](https://dev.to/ajones_codes/how-i-made-an-ios-15-safari-extension-to-get-rid-of-annoying-reddit-open-in-app-pop-ups-559p) about setting up a quick and dirty iOS 15 Safari Extension.

I forked and messed around for a while, and it definitely seems possible with the existing Safari extension.

It would require an Apple developer account, which is $100 USD a year.

**Comment by sean-public** [comment]
Check out the xcode project in this repo under `safari/recipe-filter`, it builds an app that installs a Safari extension.

I am working on publishing in the Apple App Store so everyone can install it easily.
