### ISSUE TITLE
Extension will not run on Vivaldi ?

### ISSUE THREAD

**Issue by gsd4me** [sean-public/RecipeFilter#35]
I installed the extension from the Chrome store into my Vivaldi browser 6.1.3035.257) on Windows 10 and the icon has appeared at top right next to my other extensions but when I click on that, nothing happens. I have tried restarting Vivaldi and re-booting the laptop but nothing has improved this situation. Any suggestions?

**Comment by sean-public** [comment]
Nothing should happen when you click the icon, it's a passive extension that automatically works on many recipe sites when you land on a page it knows how to help with.
