### ISSUE TITLE
Transition to Manifest V3

### ISSUE THREAD

**Issue by healsdata** [sean-public/RecipeFilter#38]
I'm going to work on a PR for this, but I wanted to open an issue first.

Recommended the extension to my wife today and she got this warning in the store:

![image](https://github.com/user-attachments/assets/f7cef549-22e0-4c2a-bc7c-3d6cd1cf911f)

I'm going to fork the code and work from this blog post to get things ready for Manifest V3

https://css-tricks.com/how-to-transition-to-manifest-v3-for-chrome-extensions/

**Comment by garyking** [comment]
Any chance the Manifest v3 version of this extension could be published to Chrome? Thanks!

**Comment by sean-public** [comment]
Submitted today 🤞 

<img width="500" alt="image" src="https://github.com/user-attachments/assets/e113565e-b1c6-4b0d-a1a2-5f6757771ea2">

<img width="500" alt="image" src="https://github.com/user-attachments/assets/2008c05b-a77e-40c1-a975-302471ff07c5">
