### ISSUE TITLE
Images unbounded on NoRecipes 

### ISSUE THREAD

**Issue by sean-public** [sean-public/RecipeFilter#5]
On NoRecipes pages like [this](https://norecipes.com/hayashi-rice), the images have no size constraints and were relying on being inside a container DIV to size them properly (they are 2000px wide), so they exceed the width of the modal RecipeFilter creates.

Possible fix: Add `max-width: 100%` for `.recipe ol li figure img` elements in CSS.

**Comment by carpii** [comment]
Kind of a similar issue here 

https://ottolenghi.co.uk/roasted-pork-belly-shop

Great extension though, thanks

**Comment by sean-public** [comment]
Thanks for reporting that one. The site has a `splash-box` element that's set to 200% width, crazy! I'll see what I can do in the next update.

**Comment by sean-public** [comment]
Works as expected now, closing old issue.
