### ISSUE TITLE
https://therecipecritic.com

### ISSUE THREAD

**Issue by produktive** [sean-public/RecipeFilter#6]
https://therecipecritic.com/2017/01/sticky-honey-garlic-butter-shrimp/

Filter fails on this page

**Comment by DaveidWeba** [comment]
Seems to work fine for me?

![image](https://user-images.githubusercontent.com/34089153/37801225-25ecf0ac-2dfc-11e8-958b-046640551b97.png)

**Comment by produktive** [comment]
Weird, now it works for me too.
