### ISSUE TITLE
showing 'dismiss' controls at top?

### ISSUE THREAD

**Issue by carpii** [sean-public/RecipeFilter#9]
1) It would be useful to show the dismiss/disable buttons at the top of the popup aswell as the bottom

Sometimes its not obvious RecipeFilter has kicked in, and it just looks like a site popup until you scroll all the way down.
Example here..

http://www.fatworksfoods.com/recipes.php

2) Hitting ESC could close the popup too. 
Oddly I noticed that hitting ESC twice on the site above, causes the popup to resize itself after which its being clipped properly.

**Comment by sean-public** [comment]
This is a great idea!

PRs with this change are welcome.

**Comment by nowheyjose** [comment]
Hey @sean-public I think I solved this. I just made a pull request. This is my first open source contribution so please let me know if it worked out. I tested these functions and it seemed to run fine.

**Comment by sean-public** [comment]
Congrats!

I hope to take a look at PRs and issues later this week and then do a release to the Chrome Web Store.

**Comment by sean-public** [comment]
This is completed!
